//
//  SharedConstant.swift
//  StaticRouteHelper
//
//  Created by 经典 on 9/1/2023.
//

import Foundation
import Blessed
import SecureXPC
import EmbeddedPropertyList


struct SharedConstant {
    //MARK: XPC START
    static let debugRoute = XPCRoute.named("debug")
    static let uninstallRoute = XPCRoute.named("uninstall")
    static let commandRoute = XPCRoute.named("command").withMessageType(RouteWriteRequest.self).withReplyType(RouteWriteReply.self).throwsType(RouterCommandError.self)
    //MARK: XPC END
    
    
    
    enum SharedConstantsError: Error {
        /// The helper tool's launchd property list's value for `MachServices` array has no elements.
        case missingMachServiceName
        /// The app's info property list is missing its `SMPrivilegedExecutables` key or has no entries in the correct format.
        case missingSMPrivilegedExecutables
        /// The app's bundled SMAppService launchd property list is missing or invalid.
        case missingSMAppServiceLaunchdPropertyList
    }
    /// Location of the helper tool's launchd property list generated by the system as part of `SMJobBless`.
    ///
    /// In practice this is where `SMJobBless` will place the launchd property list, but this behavior is not officially documented.
    let blessedPropertyListLocation: URL
    /// Location of the helper tool if it has been blessed via `SMJobBless`.
    ///
    /// In practice this is where `SMJobBless` will install the helper tool, but this behavior is not officially documented.
    let blessedLocation: URL
    
    let helperToolVersion: BundleVersion
    
    let helperToolLabel: String
    
    let jobBlessMachServiceName: String
    let appServiceLabel: String
    let appServiceMachServiceName: String
    
    #if ROUTER
    let bundledLocation: URL
    
    #endif
    
    init() throws {
    #if ROUTER
        guard let helperToolLabel = (Bundle.main.infoDictionary?["SMPrivilegedExecutables"]
                                     as? [String : Any])?.first?.key else {
            throw SharedConstantsError.missingSMPrivilegedExecutables
        }
        self.helperToolLabel = helperToolLabel
        self.bundledLocation = URL(fileURLWithPath: "Contents/Library/LaunchServices/\(helperToolLabel)",
                                   relativeTo: Bundle.main.bundleURL).absoluteURL
        let launchdPropertyList = try HelperToolLaunchdPropertyList(from: self.bundledLocation)
        let infoPropertyList = try HelperToolInfoPropertyList(from: self.bundledLocation)
        self.helperToolVersion = infoPropertyList.version
        self.blessedPropertyListLocation = URL(fileURLWithPath: "/Library/LaunchDaemons/\(helperToolLabel).plist")
        self.blessedLocation = URL(fileURLWithPath: "/Library/PrivilegedHelperTools/\(helperToolLabel)")

        guard let jobBlessMachServiceName = launchdPropertyList.machServices.first?.key else {
            throw SharedConstantsError.missingMachServiceName
        }
        self.jobBlessMachServiceName = jobBlessMachServiceName

        // SMAppService uses a dedicated launchd plist/label to avoid collisions with SMJobBless.
        let appServicePlistName = "cn.magicdian.staticrouter.service.plist"
        let appServicePlistURL = URL(
            fileURLWithPath: "Contents/Library/LaunchDaemons/\(appServicePlistName)",
            relativeTo: Bundle.main.bundleURL
        ).absoluteURL
        guard
            let plistData = try? Data(contentsOf: appServicePlistURL),
            let plist = try? PropertyListSerialization.propertyList(from: plistData, options: [], format: nil) as? [String: Any],
            let appServiceLabel = plist["Label"] as? String,
            let machServices = plist["MachServices"] as? [String: Any],
            let appServiceMachServiceName = machServices.first?.key
        else {
            throw SharedConstantsError.missingSMAppServiceLaunchdPropertyList
        }
        self.appServiceLabel = appServiceLabel
        self.appServiceMachServiceName = appServiceMachServiceName
    #else
    #if HELPER
        let launchdPropertyList = try HelperToolLaunchdPropertyList.main
        let infoPropertyList = try HelperToolInfoPropertyList.main
        self.helperToolLabel = launchdPropertyList.label
        self.helperToolVersion = infoPropertyList.version
        self.blessedPropertyListLocation = URL(fileURLWithPath: "/Library/LaunchDaemons/\(self.helperToolLabel).plist")
        self.blessedLocation = URL(fileURLWithPath: "/Library/PrivilegedHelperTools/\(self.helperToolLabel)")
        guard let jobBlessMachServiceName = launchdPropertyList.machServices.first?.key else {
            throw SharedConstantsError.missingMachServiceName
        }
        self.jobBlessMachServiceName = jobBlessMachServiceName
        self.appServiceLabel = "cn.magicdian.staticrouter.service"
        self.appServiceMachServiceName = "cn.magicdian.staticrouter.service"
    #else
        fatalError("""
        No Swift compiler directive was set for this executable. In this sample this is set in the AppConfig.xcconfig \
        and HelperToolConfig.xcconfig configuration files.
        """)
    #endif
    #endif
    }
}




extension SharedConstant {
    //MARK: XPC Service
    
}
